sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    server-->>browser: The server updates its data with the new note
    deactivate server

    Note right of browser: The browser JS callback function updates the html using DOM and re-renders the page
